In [54]:
import numpy as np
import random

In [3]:
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y=np.array([[1],[1],[0]])
print(X)

[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]


In [76]:
random.seed(1001)
W_inhn=np.random.uniform(size=(4,3))
W_hnout=np.random.uniform(size=(3,1))

binhn=np.random.uniform(size=3)
bhnout=np.random.uniform(size=1)



In [80]:
def sigmoid(x):
    return 1/(np.exp(-x)+1)
def derivative(x):
    return np.exp(-x)/(1+np.exp(-x))
print(W_inhn)
print(W_hnout)
print(binhn)
print(bhnout)

#for i in range(500):
    inhn_1=np.dot(X,W_inhn)+binhn
    inhn_2=sigmoid(inhn_1)

    hnout_1=np.dot(inhn_2,W_hnout)+bhnout
    hnout_2=sigmoid(hnout_1)


    E=y-hnout_2
    E2=np.dot(E,W_hnout.T)

    a=0.01
    prod_1=E*derivative(hnout_2)
    prod_2=np.dot(inhn_2.T,prod_1)
    prod_3=E2*derivative(inhn_2)
    prod_4=np.dot(X.T,prod_3)
    
   
    
    
    

   
    W_hnout=W_hnout+a*prod_2
    binhn=np.sum(binhn+a*prod_3,axis=0)
    W_inhn=W_inhn+a*prod_4
    bhnout=np.sum(bhnout+a*prod_1,axis=0)
    
    
print("***********")
print(W_inhn)
print(W_hnout)
print(binhn)
print(bhnout)

IndentationError: unexpected indent (<ipython-input-80-86204f12ff48>, line 11)

In [ ]:
inhn_1=np.dot(X,W_inhn)+binhn
inhn_2=sigmoid(inhn_1)

hnout_1=np.dot(inhn_2,W_hnout)+bhnout
    hnout_2=sigmoid(hnout_1)


    E=y-hnout_2
    E2=np.dot(E,W_hnout.T)

    a=0.01
    prod_1=E*derivative(hnout_2)
    prod_2=np.dot(inhn_2.T,prod_1)
    prod_3=E2*derivative(inhn_2)
    prod_4=np.dot(X.T,prod_3)
    
   
    

In [83]:
 E2=np.dot(W_hnout.T,E)

In [84]:
E2

array([[1.72522369]])